server:
  port: 8082

spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

service:
  account:
    url: http://localhost:8081
  validation:
    url: ${VALIDATION_SERVICE_URL:http://localhost:8087}

temporal:
  service:
    host: localhost
    port: 7233

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always