server:
  port: 8081

# debezium:
#   name: account-service-postgres-connector
#   connector-class: io.debezium.connector.postgresql.PostgresConnector
#   offset-storage: org.apache.kafka.connect.storage.FileOffsetBackingStore
#   offset-storage-file: ./offsets.dat
#   offset-flush-interval-ms: 60000
#   plugin-name: pgoutput
#   topic-prefix: banking
#   table-include-list: public.accounts
#   publication-name: dbz_publication
#   database:
#     hostname: localhost
#     port: "5432"
#     username: postgres
#     password: postgres
#     dbname: banking_demo

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always